- YYS/BOJ_15649.py
- YYS/BOJ_15650.py
- YYS/BOJ_15651.py
- YYS/BOJ_15652.py
> Joseph Yang / 2022 02 14 / 4문제

- YYS/BOJ_15650.py
> Joseph Yang / 2022 02 16 / 1문제

- mhlee21/BOJ_15650.py
https://www.acmicpc.net/problem/15650
> Mihyun Lee / 2022 02 16 / 1문제

- LJH/15649.py
https://www.acmicpc.net/problem/15649
> Juhyung Lee / 2022 02 16 / 1문제

- mhlee21/BOJ_1992.py
- mhlee21/BOJ_2630.py
비슷한 문제인데 분할 정복 푸는 법을 몰라서 색종이 만들기는 시간이 오래 걸렸습니다.
코드가 너무 복잡해지고 진도가 나가지 않아서 결국 구글링을 해서 해결했습니다.
덕분에 쿼드트리는 쉽게 해결했습니다 ㅎㅎ
분할 정복 푸는 법을 알고 있다면 둘 다 쉽게 해결할 수 있었던 문제 같습니다!
> Mihyun Lee / 2022 02 19 / 2문제

- JSW/BOJ_10830.py
[BOJ] 행렬제곱/ 골드4 / 3시간+a
https://www.acmicpc.net/problem/10830
아직 해결몬함 코드만 올림
전치행렬로 바꾸는 알고리즘 제거 및 최적화 진행  예정
> JSW / 2022 02 23 / 1문제

- YYS/CS_IO.md
> 입출력 시스템 정리

- JSW/BOJ_1260.py
https://www.acmicpc.net/problem/1260
> [BOJ] DFS와 BFS / 실버2 / 2시간

- LJH/BOJ_1260.py
- LJH/BOJ_7576.py
> Juhyung Lee/ 2022 03 16 / 2문제

- YYS/BOJ_1260.py
- YYS/BOJ_7576.py
DFS와 BFS)
무향 그래프일 때 인접행렬을 이용해 DFS와 BFS를 구현해 볼 수 있었습니다. Python으로 큐를 구현하는 것은 처음인데, deque를 사용한다는 것이 흥미로웠습니다.
> Joseph Yang / 2022 03 14 / 2문제

- mhlee21/BOJ_14502.py
DFS와 BFS를 함께 사용한 문제였습니다. 문제를 풀면서 계속해서 시간초과가 났는데 중복검사되는 부분을 제대로 걸러주지 못한것이 원인이었습니다. DFS 구현 시 중복검사하는 부분이 없도록 신경써서 구현해야할 것 같습니다.
> Mihyun Lee / 2022 03 18 / 1문제

- YYS/BOJ_14503.py
로봇 청소기)
2초라는 매우 널널한 시간이기에 맘놓고 풀 수 있었습니다.
처음에 이해한줄 알고 풀었는데 예제가 안풀려서 문제를 천천히 다시 읽어봤습니다.
오해한 것이 2개였습니다.
1) 로봇의 방향은 알려줄때 시계 방향으로 알려주는데 청소방향은 반시계 방향
- 시계 방향으로 풀이했었음
2) 로봇 청소기가 더이상 청소할 곳이 없는 경우 4번째로 회전한 방향 상태에서 이동
- 먼저 탐색 후 이동하도록 했는데 청소할 곳이 없는 경우 마지막 회전 방향이 아닌 처음 방향이 유지되는 문제
그래도 구현해놓은 것을 바탕으로 생각보다 일찍 수정할 수 있었습니다.
> Joseph Yang / 2022 03 20 / 1문제

- LJH/BOJ_14503.py
> Juhyung Lee/ 2022 03 21 / 1문제

- JSW/[BOJ]14503.py
[BOJ] 로봇 청소기 / 골드5 / a
https://www.acmicpc.net/problem/14503
건들지도 못했습니다 자소서 때문에 ㅠ
> Seongwoo Jeong / 2022 03 23 / 1문제

- YYS/ntw_keywords.md
> network keyword

- YYS/BOJ_14890.py
경사로)
생각이 쉽사리 나지 않아 분기문으로 풀이했습니다.
> Joseph Yang/ 2022 03 27 / 1문제

- mhlee21/BOJ_14891.py
**14891 톱니바퀴**
문제 이해가 어려웠는데 이해하고 나니 생각보다 쉬운 문제였습니다. 기준이 되는 톱니바퀴에서 왼쪽은 왼쪽으로만 검사하도록하고, 오른쪽은 오른쪽에 있는 톱니만 검사하도록 하는 부분(?) 을 생각 못해서 디버깅하는데 시간이 걸렸습니다. spin() 함수에서 현재 톱니의 번호(n)와 기준 톱니번호(gear)의 값을 비교하도록 조건을 추가해서 문제를 해결했습니다.
> Mihyun Lee / 2022 03 29 / 1문제

- YYS/BOJ_14891.py
- YYS/BOJ_15685.py
톱니바퀴)
톱니바퀴가 오른쪽으로 회전(1)하면 꼭대기에서 오른쪽에 있는 숫자로 바뀐다고 착각해서 고생했네요.. 오른쪽으로 회전하면 꼭대기 기준 왼쪽의 톱니가 꼭대기로 올라온다는 사실을 알고 고쳤더니 바로 돌아갔습니다.
드래곤 커브)
n세대 드래곤 커브를 각각 90도 회전하고 붙이면 n+1 세대 드래곤 커브가 되는 것은 알았지만 또 다시 회전에서 착각해서 혼란에 빠졌습니다. 처음에는 n세대 드래곤 커브 끝에 n세대 0인덱스 회전한 것을 붙였는데 생각해보니 n세대 드래곤 커브가 L 길이라면 L-1 인덱스부터 회전시킨다음 n세대 끝부분에 차례차례 붙이는 것으로 수정했습니다. 
또 이보다 시간을 더 많이 쏟은 이유는 pycharm에서 indexError 가 발견되지 않았는데 백준에서 indexError가 발생해 당황했습니다. 배열의 크기는 101x101이고 검사를 102x102까지 수행했는데 에러가 안떠서 전혀 오류를 생각하지 못했습니다. 이 부분은 따로 알아봐야겠네요
> Joseph Yang / 2022 03 28 / 2문제

- YYS/BOJ_17144.py
- YYS/BOJ_17779.py
- YYS/ntw_keywords.md
> Joseph Yang / 2022 04 02 / 2 문제

- mhlee21/BOJ_15685.py
- mhlee21/BOJ_17144.py
[드래곤커브]
어떻게 풀어야할지 감이 안와서 방향을 회전시킨다는 아이디어만 살짝 구글링 해보았습니다.. ^^; 아이디어를 얻고나니 생각보다 쉽게 풀렸습니다.
[미세먼지 안녕!]
읽고 이해한대로 코드를 짜봤습니다. 테스트 케이스는 다 통과하지만 백준에 제출했을때 시간초과가 났는데, python3가 아닌 pypy3로 제출하니까 통과했습니다(?) 
정답은 맞췄지만 가독성있는 코드는 아닌 것 같습니다. 좀 더 간결하고 읽기 쉬운 코드를 짜는 방법을 더 고민해봐야할 것 같습니다.
> Mihyun Lee / 2022 04 02 / 2문제

- LJH/BOJ_17144.py
https://www.acmicpc.net/problem/17144
> Juhyung Lee/ 2022 04 02 / 1문제

- LJH/BOJ_17779.py
- LJH/BOJ_19236.py
게리맨더링2는 시간 초과가 나서 해결하느라 오래 걸렸습니다.
청소년 상어는 재귀 과정에서 배열을 수정한 것이 원래 배열에 적용이 되는 것을 확인하였습니다.
> Juhyung Lee/ 2022 04 06 / 2문제

- YYS/BOJ_19236.py
- YYS/BOJ_20055.py
- YYS/ntw_keywords.md
> Joseph Yang / 2022 04 06 / 2문제

- LJH/BOJ_1717.py
입력을 받는 것을 처리하느라 시간이 오래 걸렸습니다 input()이 아닌 sys.stdin.readline으로 받아서 해결했습니다.
최단 경로 문제는 풀지 못 했습니다. 다익스트라 알고리즘과 좀 더 익숙해지고 오겠습니다.
> Juhyung Lee/ 2022 04 09 / 1문제

- mhlee21/BOJ_1504.py
- mhlee21/BOJ_1717.py
[1717 집합의 표현]
RecursionError 와 시간초과 사이에서 방법을 찾지 못해 결국 구글링해서 setrecursionlimit 을 설정하는 것으로 해결을 봤습니다..🥲
[1504 특정한 최단 경로]
제가 아직 다익스트라를 잘 이해하지 못하고 있나봅니다. 교재도 다시 읽고 구글링도 해서 풀어는봤는데... 테스트케이스만 통과되는 상태입니다.
🥲🥲🥲🥲🥲
> Mihyun Lee / 2022 04 09 / 1문제

- YYS/BOJ_1717.py
- YYS/BOJ_9372.py
> Joseph Yang / 2022 04 07 / 2문제

- YYS/13460.pypy
https://www.acmicpc.net/problem/13460
> [BOJ] 구슬탈출 2 / 골드 1 / 1시간 20분

- README.md
> schedule: Kakao Algorithm

- mhlee21/BOJ_13460.py
구슬 탈출 2... 드디어 풀었습니다....😇 
스터디 코드리뷰 내용을 토대로 거의 외워서 풀긴 했지만 아무튼! 해결하고나니 뿌듯하네요 ㅎㅎ
> Mihyun Lee / 2022 04 24 / 1문제

- LJH/PGS_다단계 칫솔 판매.py
- LJH/PGS_사라지는 발판.py
- LJH/PGS_주차 요금 계산.py
- LJH/PGS_행렬 테두리 회전하기.py
추가 안 했던 문제 추가 했습니다. 사라지는 발판은 완전히 풀지는 못 했습니다.
> Juhyung Lee/ 2022 05 11 / 4문제

- YYS/KAKAO/사라지는발판.py
사라지는 발판)
63.3 점 나왔습니다... 어느 부분이 문제인지 모르겠네요
> Joseph Yang / 2022 05 05 / 1문제

- mhlee21/[PGS] 2021 KAKAO BLIND RECRUIMENT/신규 아이디 추천.py
- mhlee21/[PGS] 2021 KAKAO BLIND RECRUIMENT/합승 택시 요금.py
**신규아이디 추천**
레벨1이라서 쉬울줄 알았으나 생각보다 시간이 오래 걸렸습니다... 파이썬이 아니었다면 풀지 못했을 것 같습니다. ㅎㅎㅎ
**합승 택시 요금**
플로이드 와샬 알고리즘을 오랜만에 다시 공부했습니다. 이 알고리즘을 기억만 하고 있었더라면..! 금방 풀수 있는 문제였을텐데, 왜 항상 기억이 안나는걸까요...
> Mihyun Lee / 2022 05 13 / 2문제

- YYS/KAKAO/신규 아이디 추천.py
- YYS/KAKAO/합승택시요금.py
> Joseph Yang / 2022 05 12 / 2 문제

- CS/Network/Network 면접 준비.md
> 0514 Network 스터디

- YYS/BOJ_24444.py
- YYS/BOJ_24445.py
- YYS/BOJ_24479.py
- YYS/BOJ_24480.py
> Joseph Yang / 2022 06 20 / 4문제

- YYS/BOJ_10942.py
- YYS/BOJ_11066.Py
- YYS/BOJ_1520.py
- YYS/BOJ_2629.py
> Joseph Yang / 2022 06 27 / 4문제

- YYS/MIDAS_개발자진단.py
> Joseph Yang / 2022 06 28 / 1문제

- mhlee21/BOJ_10942.py
- mhlee21/BOJ_11066.py
> Mihyun Lee / 2022 06 29 / 2문제

- LJH/PGS_순위 검색.py
> Juhyung Lee/ 2022 07 02 / 1문제

- JSW/[PGS]순위검색.py
[PGS]순위검색
https://programmers.co.kr/learn/courses/30/lessons/72412
> seongwoo Jeong/ 2022 07 02 / 1문제

- mhlee21/[PGS] 2021 KAKAO BLIND RECRUIMENT/순위 검색.py
- mhlee21/[PGS] 2021 KAKAO BLIND RECRUIMENT/카드 짝 맞추기.py
* 순위검색
* 카드 짝 맞추기는 두번째 test case 디버깅 중 입니다
> Mihyun Lee / 2022 07 02 / 1문제

- YYS/KAKAO/카드짝맞추기.py
> Joseph Yang / 2022 07 01 / 1문제

- YYS/KAKAO/광고삽입.py
> Joseph Yang / 2022 07 02 / 1문제

- YYS/KAKAO/광고삽입.py
- YYS/KAKAO/자물쇠와 열쇠.py
> Joseph Yang / 2022 07 04 / 2문제

- LJH/PGS_문자열 압축.py
- LJH/PGS_자물쇠와 열쇠.py
자물쇠와 열쇠 문제에서 numpy 라이브러리 사용해봤습니다
> Juhyung Lee/ 2022 07 06 / 2문제

- README.md
- YYS/KAKAO/괄호 변환.py
> Joseph Yang / 2022 07 14 / 1문제

- LJH/PGS_괄호 변환.py
> Juhyung Lee/ 2022 07 16 / 1문제

- mhlee21/[PGS] 2020 KAKAO BLIND RECRUITMENT/괄호 변환.py
[PGS] 괄호 변환 / level2 / 30분
문제에서 주어진 알고리즘을 그대로 코드로 옮겨서 풀었습니다.
주어진 알고리즘이 없었다면 풀지 못했을 것 같습니다.
사실 문제의 알고리즘은 아직 이해를 못했습니다. 😇
> Mihyun Lee / 2022 07 16 / 1문제

- YYS/KAKAO/기둥과보설치.java
기둥과 보 설치)
어휴 조건이 참.. 연속된 보 위에도 기둥을 설치할 수 있군요
> Joseph Yang / 2022 07 20 / 1문제

- LJH/DB/데이터베이스.md
> Juhyung Lee/ 2022 07 21 / DB 기술면접 질문 정리 1

- JSW/sql/트랜잭션 이전까지.md
> Jeong SeongWoo / 2022 07 23 / SQL_Learn

- YYS/JAVA/java면접.md
> Joseph Yang / 08 02 / JAVA 면접 대비

- YYS/낚시터자리잡기.java
낚시터 자리잡기)
실수1: 낚시터에 사람이 1일 때 최소거리가 1로 끝나는 엣지 케이스 고려X
> Joseph Yang / 2022 08 27 / 2문제

- README.md
> 2022 09 23 README 업데이트
